export const ClassNames = {
  ButtonSmall: "button-small",
  ButtonSubmit: "button-submit",
  ButtonSubmitIncorrect: "button-submit-incorrect",
  LoadingCell: "loading-cell",
  LoadingIcon: "loading-icon",
  Main: "main",
  MainInner: "main-inner",
  Page: "page",
  PageImage: "page-image",
  Pages: "pages",
  Puzzle: "puzzle",
  PuzzleCorrect: "puzzle-correct",
  PuzzleCorrectBoom: "puzzle-correct-boom",
  PuzzleCorrectEmojiStorm: "puzzle-correct-emoji-storm",
  PuzzlePrompt: "puzzle-prompt",
  PuzzleFieldset: "puzzle-fieldset",
  PuzzleForm: "puzzle-form",
  PuzzleInputDigit: "puzzle-input-digit",
  PuzzleInputPrefix: "puzzle-input-prefix",
  PuzzleInputSuffix: "puzzle-input-suffix",
  PuzzleInputText: "puzzle-input-text",
  RtlHint: "rtl-hint",
  Topbar: "topbar",
};
